{
  "compute_environment": "LOCAL_MACHINE",
  "debug": false,
  "distributed_type": "MULTI_GPU",
  "downcast_bf16": false,
  "fsdp_config": {
    "fsdp_auto_wrap_policy": "TRANSFORMER_BASED_WRAP",
    "fsdp_backward_prefetch_policy": "BACKWARD_PRE",
    "fsdp_forward_prefetch": false,
    "fsdp_cpu_ram_efficient_loading": true,
    "fsdp_offload_params": false,
    "fsdp_sharding_strategy": "FULL_SHARD",
    "fsdp_state_dict_type": "SHARDED_STATE_DICT",
    "fsdp_sync_module_states": true,
    "fsdp_transformer_layer_cls_to_wrap": "DiTBlock",
    "fsdp_use_orig_params": true
  },
  "enable_cpu_affinity": false,
  "machine_rank": 0,
  "main_training_function": "main",
  "mixed_precision": "bf16",
  "num_machines": 1,
  "num_processes": 8,
  "rdzv_backend": "c10d",
  "same_network": true,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false
}
